### ISSUE TITLE
build_rpi_armv6_lib.sh fails

### ISSUE THREAD

**Issue by rushil791** [cloudwiser/TensorFlowLiteRPIZero#1]
Hi,

Not sure why but every single time I run the script after downloading dependencies, the script comes up with multiple errors.

I build before but I had to reflash my sd, but now I can't reproduce in time for a deadline. Please help!

The error output:

`./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:31: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                               ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:67: error: expected primary-expression before ‘float’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:68: error: expected primary-expression before ‘float’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:68: error: expected primary-expression before ‘float’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
In file included from tensorflow/lite/kernels/add.cc:19:0:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function ‘void tflite::optimized_ops::LstmCell(const tflite::LstmCellParams&, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, tflite::CpuBackendContext*)’:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:31: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                               ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:67: error: expected primary-expression before ‘float’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:68: error: expected primary-expression before ‘float’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:68: error: expected primary-expression before ‘float’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function ‘void tflite::optimized_ops::Logistic(const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*)’:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:35: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:71: error: expected primary-expression before ‘float’
       input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                                                       ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function ‘void tflite::optimized_ops::Logistic(const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*)’:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:35: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:71: error: expected primary-expression before ‘float’
      input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                                                      ^~~~~
arm-linux-gnueabihf-g++ -O3 -DNDEBUG -fPIC  --std=c++11 -march=armv6 -mfpu=vfp -funsafe-math-optimizations -ftree-vectorize -fPIC -I. -I/home/pi/tensorflow/tensorflow/lite/tools/make/../../../../../ -I/home/pi/tensorflow/tensorflow/lite/tools/make/../../../../../../ -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/ -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/absl -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/gemmlowp -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/neon_2_sse -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/farmhash/src -I/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/kernels/arg_min_max.cc -o /home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/arg_min_max.o`

`In file included from /home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/Core:388:0,
                 from ./third_party/eigen3/Eigen/Core:1,
                 from ./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:36,
                 from tensorflow/lite/kernels/activations.cc:25:
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/CoreEvaluators.h: In instantiation of ‘Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::CoeffReturnType Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::coeff(Eigen::Index, Eigen::Index) const [with BinaryOp = Eigen::internal::scalar_difference_op<float, float>; Lhs = const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >; Rhs = const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1>; typename Eigen::internal::traits<typename Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Rhs>::Scalar = float; typename Eigen::internal::traits<typename Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Lhs>::Scalar = float; Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::CoeffReturnType = float; Eigen::Index = int]’:
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/CoreEvaluators.h:1328:36:   required from ‘Eigen::internal::evaluator_wrapper_base<XprType>::CoeffReturnType Eigen::internal::evaluator_wrapper_base<XprType>::coeff(Eigen::Index, Eigen::Index) const [with XprType = Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >; Eigen::internal::evaluator_wrapper_base<XprType>::CoeffReturnType = float; Eigen::Index = int]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/CoreEvaluators.h:713:74:   required from ‘Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::CoeffReturnType Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::coeff(Eigen::Index, Eigen::Index) const [with BinaryOp = Eigen::internal::scalar_product_op<float, float>; Lhs = const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >; Rhs = const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> >; typename Eigen::internal::traits<typename Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Rhs>::Scalar = float; typename Eigen::internal::traits<typename Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Lhs>::Scalar = float; Eigen::internal::binary_evaluator<Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>, Eigen::internal::IndexBased, Eigen::internal::IndexBased>::CoeffReturnType = float; Eigen::Index = int]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:631:5:   required from ‘void Eigen::internal::generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version>::assignCoeff(Eigen::Index, Eigen::Index) [with DstEvaluatorTypeT = Eigen::internal::evaluator<Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> > >; SrcEvaluatorTypeT = Eigen::internal::evaluator<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > > >; Functor = Eigen::internal::assign_op<float, float>; int Version = 0; Eigen::Index = int]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:645:16:   required from ‘void Eigen::internal::generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version>::assignCoeffByOuterInner(Eigen::Index, Eigen::Index) [with DstEvaluatorTypeT = Eigen::internal::evaluator<Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> > >; SrcEvaluatorTypeT = Eigen::internal::evaluator<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > > >; Functor = Eigen::internal::assign_op<float, float>; int Version = 0; Eigen::Index = int]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:326:9:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:862:31:   required from ‘static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >; SrcXprType = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > >; Functor = Eigen::internal::assign_op<float, float>; Weak = void]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:813:49:   required from ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >; Src = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > >; Func = Eigen::internal::assign_op<float, float>]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:776:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >; Src = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > >; Func = Eigen::internal::assign_op<float, float>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/AssignEvaluator.h:754:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >; Src = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > >]’
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/Assign.h:66:28:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::ArrayWrapper<Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Array<float, -1, -1> > >; Derived = Eigen::Map<Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >]’
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3416:73:   required from here
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/CoreEvaluators.h:713:74: error: no match for call to ‘(const Eigen::internal::scalar_difference_op<float, float>) (Eigen::internal::mapbase_evaluator<Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, const Eigen::Matrix<float, -1, -1> >::CoeffReturnType, Eigen::internal::unary_evaluator<Eigen::Replicate<Eigen::PartialReduxExpr<const Eigen::Map<const Eigen::Matrix<float, -1, -1>, 0, Eigen::Stride<0, 0> >, Eigen::internal::member_maxCoeff<float>, 0>, -1, 1>, Eigen::internal::IndexBased, float>::CoeffReturnType)’
     return m_functor(m_lhsImpl.coeff(row, col), m_rhsImpl.coeff(row, col));
                                                                          ^
/home/pi/tensorflow/tensorflow/lite/tools/make/downloads/eigen/Eigen/src/Core/CoreEvaluators.h:822: confused by earlier errors, bailing out
tensorflow/lite/tools/make/Makefile:216: recipe for target '/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/activations.o' failed
make: *** [/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/activations.o] Error 1
In file included from tensorflow/lite/kernels/arg_min_max.cc:17:0:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function ‘void tflite::optimized_ops::LstmCell(const tflite::LstmCellParams&, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, const tflite::RuntimeShape&, float*, tflite::CpuBackendContext*)’:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:31: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                               ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2500:67: error: expected primary-expression before ‘float’
       input_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2502:68: error: expected primary-expression before ‘float’
       forget_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:32: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:2505:68: error: expected primary-expression before ‘float’
       output_gate_sm.unaryExpr(Eigen::internal::scalar_logistic_op<float>()) *
                                                                    ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h: In function ‘void tflite::optimized_ops::Logistic(const tflite::RuntimeShape&, const float*, const tflite::RuntimeShape&, float*)’:
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:35: error: ‘scalar_logistic_op’ is not a member of ‘Eigen::internal’
       input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                   ^~~~~
./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3760:71: error: expected primary-expression before ‘float’
       input_map.array().unaryExpr(Eigen::internal::scalar_logistic_op<float>());
                                                                       ^~~~~
tensorflow/lite/tools/make/Makefile:216: recipe for target '/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/arg_min_max.o' failed
make: *** [/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/arg_min_max.o] Error 1
`
`

**Comment by rushil791** [comment]
Managed to fix, I reverted back to a previous version of Tensorflow Lite.

**Comment by cloudwiser** [comment]
Thanks for the heads-up - appreciate this is a long-overdue response - I'll try with the latest version of TF Lite and see if I can reproduce and resolve
