### ISSUE TITLE
fails to compile missing header file (gtest/gtest.h)

### ISSUE THREAD

**Issue by val-storm** [cloudwiser/TensorFlowLiteRPIZero#2]
Installed tensorflow dependencies by changing the eigen mirror 
https://github.com/tensorflow/tensorflow/commit/05514a000a017dbe7db7643d084b16def9719c99

started the build script and I get this error mid-compile
```
tensorflow/lite/kernels/test_main.cc:17:25: fatal error: gtest/gtest.h: No such file or directory
 #include <gtest/gtest.h>
                         ^
compilation terminated.
tensorflow/lite/tools/make/Makefile:216: recipe for target '/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/test_main.o' failed
make: *** [/home/pi/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/obj/tensorflow/lite/kernels/test_main.o] Error 1
```

**Comment by rushil791** [comment]
Had a similar issue, instead of changing the Eigen mirror entirely, change http to https on the EIGEN_URL line when editing download_dependencies.sh. It fixed the gtest error for me, but I got way more.

**Comment by cloudwiser** [comment]
Closing this issue as it seems to be down to an underlying TF build dependency. Feel free to reopen if you are still having problems - thanks
