### ISSUE TITLE
/bin folder is not created

### ISSUE THREAD

**Issue by jasalazar** [cloudwiser/TensorFlowLiteRPIZero#4]
Running your script does not create a `bin` folder, and I assume neither of the components that should be created inside. Instead, an `obj` folder is created, but it contains none of the files you mention.

Furthermore, I am recreating these steps on a Google Vision Kit. However, when I run my .tflite file, it throws `ModuleNotFoundError: No module named 'aiy'`.

Does it matter where in the system I recreate these steps to be able to use AIY's libraries?

**Comment by cloudwiser** [comment]
No - these would be created by either the repo clone or the C++ make process for samples mentioned (I can't recall which)
However, this was not tested with Google Vision AIY so it is probably best to seek help in their repo. 
The tflite file is the model so I assume you are running a python script - checking your ``PYTHONPATH`` environment variable to ensure it contains the path to ``aiy`` might help
